<a href="https://colab.research.google.com/github/Pramuuu/Daily-tasks/blob/main/25_06_2024_numpy_array_broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
print(np.__version__)

1.25.2


In [4]:
import numpy as np
x=np.arange(2,6).reshape(4)
print(x)


[2 3 4 5]


In [6]:
import numpy as np
x=np.arange(2,10).reshape(2,4)
print(x)

[[2 3 4 5]
 [6 7 8 9]]


In [8]:
import numpy as np
x=np.arange(24).reshape(4,3,2)
print(x)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [9]:
import numpy as np
l=[12.12,12.32,100,36.334]
a=np.array(l)
print(a)

[ 12.12   12.32  100.     36.334]


In [11]:
import numpy as np
x=np.arange(2,11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [12]:
import numpy as np
x=np.arange(12,23)
print(x)

[12 13 14 15 16 17 18 19 20 21 22]


In [14]:
a = np.array([1, 2, 3], dtype=np.float32)
print(a)
print(a.dtype)

[1. 2. 3.]
float32


In [15]:
import numpy as np
a = np.float32(2.0)
a
2.0
b = np.int_([3, 5, 7])
b

array([3, 5, 7])

In [16]:
import numpy as np
np.array([3, 5, 7], dtype='f')


array([3., 5., 7.], dtype=float32)

In [17]:
import numpy as np
c = np.arange(5, dtype=np.uint8)
(c.astype(float))

array([0., 1., 2., 3., 4.])

In [18]:
import numpy as np
x = np.array([3, 5], dtype=np.float32)
np.asarray(x, dtype=np.float32) is x

True

In [19]:
np.asarray(x, dtype=np.float64) is a

False

In [20]:
a=[2,3,4,5,6,7,8,9]
b=np.asarray(a)
print(b)

[2 3 4 5 6 7 8 9]


In [21]:
a=(10,20,30)
b=np.asarray(a)
print(b)

[10 20 30]


In [22]:
import numpy as np
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [23]:
np.ones((2, 1))


array([[1.],
       [1.]])

In [24]:
np.ones(7,)

array([1., 1., 1., 1., 1., 1., 1.])

In [25]:
x = (2, 3)
np.ones(x)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [26]:
import numpy as np
a = (3, 2)
array = np.zeros(a)
print(array)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [27]:
import numpy as np
array = np.zeros((6,), dtype=int)
print(array)

[0 0 0 0 0 0]


In [28]:

import numpy as np
nums = np.zeros((2, 3, 4), dtype=int)
nums[:, 1, :] = 2
print(nums)

[[[0 0 0 0]
  [2 2 2 2]
  [0 0 0 0]]

 [[0 0 0 0]
  [2 2 2 2]
  [0 0 0 0]]]


In [29]:
np.empty([2, 2])

array([[1., 2.],
       [3., 4.]])

In [30]:
np.empty([2, 3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
import numpy as np
np.empty(2)

array([1., 1.])

In [32]:
import numpy as np
x = np.array([1, 2, 3])
y = np.array([[10], [20], [30]])
result = x + y
print(result)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [33]:

import numpy as np
x = np.array([[5, 6, 7, 8], [1, 2, 3, 4], [9, 10, 11, 12]])
y = np.array([1, 2, 3, 4])
result = x - y
print("2D Array x:\n", x)
print("1D Array y:\n", y)
print("Result of x - y:\n", result)

2D Array x:
 [[ 5  6  7  8]
 [ 1  2  3  4]
 [ 9 10 11 12]]
1D Array y:
 [1 2 3 4]
Result of x - y:
 [[4 4 4 4]
 [0 0 0 0]
 [8 8 8 8]]
