<a href="https://colab.research.google.com/github/Pramuuu/Daily-tasks/blob/main/27_06_2024_array_operations%2Cindexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#numpy operations
#multiplication
import numpy as np
p=[[1,0], [0,1]]
q=[[1,2],[3,4]]
result = np.dot(p,q)
print(result)

[[1 2]
 [3 4]]


In [ ]:
import numpy as np
print(np.add(1.0,4.0))

print(np.subtract(1.0,4.0))

print(np.multiply(1.0,4.0))

print(np.divide(1.0,4.0))

5.0
-3.0
4.0
0.25


In [2]:
import numpy as np
a=np.array([2,3,4,5])
b=a*2
print(b)
c=a/2
print(c)

[ 4  6  8 10]
[1.  1.5 2.  2.5]


In [3]:
import numpy as np
l1=np.log(1e-50)
l2=np.log(2.5e-50)
print(np.logaddexp(l1,l2))
print(np.logaddexp2(l1,l2))

-113.87649168120691
-113.59955522772194


In [4]:
import numpy as np
x=np.arange(7)
print(x)
print(np.power(x,3))

[0 1 2 3 4 5 6]
[  0   1   8  27  64 125 216]


In [5]:
#absolute value
import numpy as np
x=np.array([-10.2,122.2,.20])
print(x)
print(np.absolute(x))

[-10.2 122.2   0.2]
[ 10.2 122.2   0.2]


In [8]:
#indexing
import numpy as np
array_2d  = np.random.randint(0,100, size =(5,5))
threshold =50
selected_elements = array_2d[array_2d>threshold]
print('Original 2D array:\n', array_2d)
print(f'\nElements greater than {threshold}:\n', selected_elements)

Original 2D array:
 [[88 60 77 79 22]
 [64 96 89 37 41]
 [78 47 95 43 47]
 [92 69 71 26 60]
 [38 85 68 38 60]]

Elements greater than 50:
 [88 60 77 79 64 96 89 78 95 92 69 71 60 85 68 60]


In [9]:
import numpy as np
array_1d = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
index_array = np.array([0, 2, 4, 6, 8])
selected_elements = array_1d[index_array]
print('Original 1D array:\n', array_1d)
print('Index array:\n', index_array)
print('Selected elements:\n', selected_elements)

Original 1D array:
 [ 10  20  30  40  50  60  70  80  90 100]
Index array:
 [0 2 4 6 8]
Selected elements:
 [10 30 50 70 90]


In [10]:
import numpy as np
array_3d = np.random.randint(0, 100, size=(4, 5, 6))
slice_2d = array_3d[2, :, :]
row_indices = np.array([0, 2, 4])
col_indices = np.array([1, 3, 5])
selected_elements = slice_2d[row_indices, col_indices]
print('Original 3D array:\n', array_3d)
print('2D slice (3rd slice along first axis):\n', slice_2d)
print('Row indices:', row_indices)
print('Column indices:', col_indices)
print('Selected elements from 2D slice:\n', selected_elements)

Original 3D array:
 [[[46 76 69 64 25 69]
  [72 64 65 73 63 73]
  [58 26 32 27 22 22]
  [35 68 25 10 96 80]
  [26 52 67 64 81 16]]

 [[19 46 34 20 49  3]
  [ 8 50 95 22 65 95]
  [70  3 17 93 91 12]
  [18 47 93  9 60 74]
  [79 41 17 56  8 29]]

 [[30 29 70 64 27 57]
  [46 54 61 22 71  4]
  [67 10 34  7 59 68]
  [94 58 49 53 24 39]
  [72 56  2 91 23 38]]

 [[91 78 96 41 20 72]
  [66 93 93 52 30 65]
  [19 31 96 91 16 62]
  [76 79 13 84 24 45]
  [11  6 83 24 59 15]]]
2D slice (3rd slice along first axis):
 [[30 29 70 64 27 57]
 [46 54 61 22 71  4]
 [67 10 34  7 59 68]
 [94 58 49 53 24 39]
 [72 56  2 91 23 38]]
Row indices: [0 2 4]
Column indices: [1 3 5]
Selected elements from 2D slice:
 [29  7 38]


In [11]:
import numpy as np
array_2d = np.random.randint(0, 100, size=(6, 6))
row_indices = np.arange(2, 5)
col_indices = np.arange(1, 4)
subarray = array_2d[row_indices[:, np.newaxis], col_indices]
print('Original 2D array:\n', array_2d)
print('Row indices:', row_indices)
print('Column indices:', col_indices)
print('Selected subarray:\n', subarray)

Original 2D array:
 [[ 7 10 61 73 65 17]
 [56 39 23 42  5 56]
 [47 32 91 73 15 90]
 [87 96 42 79 59  3]
 [96 28 55 48 94 95]
 [51  3 41  5 22  4]]
Row indices: [2 3 4]
Column indices: [1 2 3]
Selected subarray:
 [[32 91 73]
 [96 42 79]
 [28 55 48]]


In [12]:
import numpy as np
original_1d_array = np.arange(20)
print("Original 1D array:\n", original_1d_array)
reshaped_matrix = original_1d_array.reshape(4, 5)
print("\nReshaped (4, 5) matrix:\n", reshaped_matrix)
sub_matrix = reshaped_matrix[:2, :3]
print("\nSliced (2, 3) sub-matrix:\n", sub_matrix)
print("\nStrides of the sub-matrix:\n", sub_matrix.strides)

Original 1D array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Reshaped (4, 5) matrix:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Sliced (2, 3) sub-matrix:
 [[0 1 2]
 [5 6 7]]

Strides of the sub-matrix:
 (40, 8)


In [13]:
#fancy indexing
import numpy as np
array_3d = np.random.randint(0, 100, size=(3, 4, 5))
row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 3])
selected_elements = array_3d[row_indices[:, np.newaxis], col_indices]
print('Original 3D array:\n', array_3d)
print('Row indices:\n', row_indices)
print('Column indices:\n', col_indices)
print('Selected elements:\n', selected_elements)

Original 3D array:
 [[[48 52 64 83 55]
  [96 57 83  9 62]
  [63 28 70 67 51]
  [15 74 76 26 28]]

 [[73 68 66 67 68]
  [96 60 36  8 68]
  [93 93 75 71 95]
  [32 23 75 57 95]]

 [[52 60 42 92 20]
  [11 95 14 22 55]
  [ 8 34 49 45  4]
  [93 34 71 94  0]]]
Row indices:
 [0 1 2]
Column indices:
 [1 2 3]
Selected elements:
 [[[96 57 83  9 62]
  [63 28 70 67 51]
  [15 74 76 26 28]]

 [[96 60 36  8 68]
  [93 93 75 71 95]
  [32 23 75 57 95]]

 [[11 95 14 22 55]
  [ 8 34 49 45  4]
  [93 34 71 94  0]]]


In [14]:
import numpy as np
array = np.arange(30, 71, 2)
print("Array of all the even integers from 30 to 70")
print(array)


Array of all the even integers from 30 to 70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [15]:
import numpy as np
arrays = [np.random.randn(2, 3) for _ in range(8)]
result = np.stack(arrays, axis=0)
print(result.shape)

(8, 2, 3)


In [16]:
import numpy as np
arrays = [np.random.randn(2, 3) for _ in range(8)]
result_axis_1 = np.stack(arrays, axis=1)
result_axis_2 = np.stack(arrays, axis=2)
print(result_axis_1.shape)
print(result_axis_2.shape)


(2, 8, 3)
(2, 3, 8)


In [17]:
import numpy as np
x = np.array([2, 3, 4])
y = np.array([3, 4, 5])
result_default = np.stack((x, y))
result_axis_neg1 = np.stack((x, y), axis=-1)
print(result_default)
print(result_axis_neg1)

[[2 3 4]
 [3 4 5]]
[[2 3]
 [3 4]
 [4 5]]


In [18]:
import numpy as np
print("\nOriginal arrays:")
x = np.arange(9).reshape(3, 3)
y = x * 3
print("Array-1")
print(x)
print("Array-2")
print(y)
new_array = np.hstack((x, y))
print("\nStack arrays in sequence horizontally:")
print(new_array)


Original arrays:
Array-1
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Array-2
[[ 0  3  6]
 [ 9 12 15]
 [18 21 24]]

Stack arrays in sequence horizontally:
[[ 0  1  2  0  3  6]
 [ 3  4  5  9 12 15]
 [ 6  7  8 18 21 24]]


In [ ]:
#np.array
#np.size
#dtype
#np.asarray()
#np.ones
#np.zeros
#np.empty
#np.arange()
#np.linspace()
#np.eye()

In [21]:
import numpy as np
a = np.arange(2, 8).reshape(3, 2)
a
a.flat[4]
a.T
a.T.flat[4]
type(a.flat)

numpy.flatiter